Update patch set 1
Patch Set 1: Code-Review-1

java/app_test.go fails with the following errors:

FAILED: <builddir>/out/soong/.bootstrap/soong-java/test/test.passed
<builddir>/out/soong/.bootstrap/bin/gotestrunner -p ./build/soong/java -f <builddir>/out/soong/.bootstrap/soong-java/test/test.passed -- <builddir>/out/soong/.bootstrap/soong-java/test/test -test.short
--- FAIL: TestAndroidAppImport (0.02s)
    app_test.go:1184: Incorrect signing flags, expected: "build/make/target/product/security/platform.x509.pem build/make/target/product/security/platform.pk8", got: "build/target/product/security/platform.x509.pem build/target/product/security/platform.pk8"
--- FAIL: TestAndroidAppImport_DefaultDevCert (0.01s)
    app_test.go:1268: Incorrect signing flags, expected: "build/make/target/product/security/testkey.x509.pem build/make/target/product/security/testkey.pk8", got: "build/target/product/security/testkey.x509.pem build/target/product/security/testkey.pk8"
FAIL
12:30:12 soong bootstrap failed with: exit status 1
make: *** [build/make/core/main.mk:21: run_soong_ui] Error 1

there's a need to properly fix those tests

Patch-set: 1
Reviewer: Gerrit User 1000003 <1000003@d5cc2900-f5de-4894-bcd1-c35edbbdd7bf>
Label: Code-Review=-1